name: CI — Build and Push to ACR

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ping:1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Run tests
        working-directory: ./server
        run: npm test
        env:
          NODE_ENV: test
          MONGO_URI: mongodb://localhost:27017/ecommerce-test
      - name: Check secrets
        run: |
          echo "Registry length: ${#REGISTRY}"
          if [ -z "$REGISTRY" ]; then
            echo "REGISTRY IS EMPTY!"
          else
            echo "REGISTRY IS SET"
          fi
        env:
          REGISTRY: ${{ secrets.REGISTRY_LOGIN_SERVER }}    

      - name: Build and push server image
        run: |
          REGISTRY="ecommerceregistryad2024.azurecr.io"
          docker build -t $REGISTRY/server:${{ github.sha }} -t $REGISTRY/server:latest ./server
          docker push $REGISTRY/server:${{ github.sha }}
          docker push $REGISTRY/server:latest

      - name: Build and push client image
        run: |
          REGISTRY="ecommerceregistryad2024.azurecr.io"
          docker build \
            --build-arg VITE_API_URL=http://${{ secrets.INGRESS_IP }}/api \
            -t $REGISTRY/client:${{ github.sha }} \
            -t $REGISTRY/client:latest ./client
          docker push $REGISTRY/client:${{ github.sha }}
          docker push $REGISTRY/client:latest